### ISSUE TITLE
Produce compressed messages

### ISSUE THREAD

**Issue by pnicolauc** [marcosandremartins/rest-producer#10]
**Use case**

Produce a message with client side compression

**Example**

Protobuf message that needs to be compressed with gzip before producing

**Comment by marcosandremartins** [comment]
Under review: https://github.com/marcosandremartins/rest-producer/pull/12

**Comment by marcosandremartins** [comment]
Pull request https://github.com/marcosandremartins/rest-producer/issues/10 merged
